services:
  fireshare:
    container_name: fireshare
    image: shaneisrael/fireshare:latest
    ports:
      - "8080:80"
    volumes:
      - ./dev_root/fireshare_data:/data
      - ./dev_root/fireshare_processed:/processed
      - ./dev_root/fireshare_videos:/videos
    environment:
      - ADMIN_PASSWORD=admin
      - MINUTES_BETWEEN_VIDEO_SCANS=5
      - PUID=1000
      - PGID=1000
