name: Publish Docker Image
on:
  push:
    branches: [main]
    paths:
      - "app/**"
  workflow_dispatch:
    tag:
      description: The build tag to push.
      required: true
      default: "latest"
jobs:
  push_to_registry:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: shaneisrael/fireshare:latest
  manual_push_to_registry:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: shaneisrael/fireshare:${{ github.event.inputs.tag }}
